# .github/workflows/release.yml
name: Release Go Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Build binaries
        run: make build VERSION=${{ github.ref_name }}
        
      - name: Package artifacts
        run: |
          # Crea un directorio para los archivos comprimidos
          mkdir -p release_packages
          
          # Comprime cada conjunto de binarios en un archivo tar.gz o .zip
          cd dist/${{ github.ref_name }}
          tar -czf ../../release_packages/azdevops_linux_amd64.tar.gz -C linux-amd64 .
          tar -czf ../../release_packages/azdevops_linux_arm64.tar.gz -C linux-arm64 .
          tar -czf ../../release_packages/azdevops_darwin_amd64.tar.gz -C darwin-amd64 .
          tar -czf ../../release_packages/azdevops_darwin_arm64.tar.gz -C darwin-arm64 .
          zip -r ../../release_packages/azdevops_windows_amd64.zip windows-amd64

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release_packages/*"
          bodyFile: "RELEASE_NOTES.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
